#!/usr/bin/env sh
# Concatenate the source into a single dependency-free stylesheet, then stamp
# the specimen page with a build id.
#
# The build id is a content hash of dist/s-bahn.css plus demo/index.html (with
# the stamp line itself excluded, so it is not circular). It changes exactly
# when what the page shows changes, and it is reproducible: run this twice and
# nothing moves. It is deliberately not the git commit — a file cannot carry
# its own commit's SHA, and stamping the previous commit would mislead.
set -eu
cd "$(dirname "$0")"
OUT=dist/s-bahn.css
DEMO=demo/index.html
TOKENS="fonts colors typography spacing borders base"
COMPONENTS="actions forms containers data feedback navigation"
VERSION=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' package.json)

mkdir -p dist
{
  # Every @import must precede all other rules, so the font import leads.
  grep -h '^@import' src/tokens/fonts.css
  echo
  echo "/* s-bahn-stuttgart v$VERSION — generated by build.sh. Do not edit. */"
  for t in $TOKENS; do
    echo; echo "/* ===== tokens/$t.css ===== */"
    grep -v '^@import' "src/tokens/$t.css"
  done
  for c in $COMPONENTS; do
    echo; echo "/* ===== components/$c.css ===== */"
    cat "src/components/$c.css"
  done
} > "$OUT"

# sha256sum on Linux, shasum on macOS.
if command -v sha256sum >/dev/null 2>&1; then H=sha256sum; else H="shasum -a 256"; fi
ID=$( { cat "$OUT"; grep -v 'id="build-stamp"' "$DEMO"; } | $H | cut -c1-8 )
STAMP="  <p id=\"build-stamp\" class=\"sb-mono\" style=\"color:var(--text-faint);margin:var(--space-1) 0 0\">v$VERSION · build $ID</p>"
awk -v s="$STAMP" '/id="build-stamp"/{print s;next}{print}' "$DEMO" > "$DEMO.tmp" && mv "$DEMO.tmp" "$DEMO"

echo "$OUT: $(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes"
echo "build id: $ID  (v$VERSION)"
