#!/usr/bin/env sh
# Concatenate the source into a single dependency-free stylesheet.
# No minifier, no toolchain: the output stays readable and diffable.
set -eu
cd "$(dirname "$0")"
OUT=dist/s-bahn.css
TOKENS="fonts colors typography spacing borders base"
COMPONENTS="actions forms containers data feedback navigation"

mkdir -p dist
{
  # Every @import must precede all other rules, so the font import leads.
  grep -h '^@import' src/tokens/fonts.css
  echo
  echo "/* s-bahn-stuttgart — generated by build.sh. Do not edit. */"
  for t in $TOKENS; do
    echo; echo "/* ===== tokens/$t.css ===== */"
    grep -v '^@import' "src/tokens/$t.css"
  done
  for c in $COMPONENTS; do
    echo; echo "/* ===== components/$c.css ===== */"
    cat "src/components/$c.css"
  done
} > "$OUT"

echo "$OUT: $(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes"
